[project]
name = 'Multiverse-Ecosystem-Simulator'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ecosystem-management]
path = 'contracts/ecosystem-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.simulation-marketplace]
path = 'contracts/simulation-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.species-nft]
path = 'contracts/species-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
